name: terraform
on:
  push:
    branches: 
    - "main" 
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest 

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: terraform initialize
        working-directory: terraform
        run: |
          terraform init 
          


      # Runs a single command using the runners shell
      - name: terraform validate
        working-directory: terraform
        run: |
          terraform validate 




      # Runs a single command using the runners shell
      - name: terraform build
        working-directory: terraform
        run: |
          terraform apply -auto-approve
          packer build image.pkr.hcl