name: Pipeline1
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Packer initialize
        working-directory: packer
        run: |
          packer init . 
          packer validate . 