name: packer
on:
  push:
    branches: 
    - "main" 
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest 

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Packer initialize
        working-directory: packer
        run: |
          packer init  .
          


      # Runs a single command using the runners shell
      - name: Packer validate
        working-directory: packer
        run: |
          packer validate . 




      # Runs a single command using the runners shell
      - name: Packer build
        working-directory: packer
        run: |
          packer build image.pkr.hcl